version: '3.3'

services:

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"

  app1:
    build: ./app1
    container_name: app1
    restart: always
    expose:
      - 8080

  app2:
    build: ./app2
    container_name: app2
    restart: always
    expose:
      - 8081
